SELECT TOP (1000) [CertificateID]
      ,[ChildName]
      ,[DateOfBirth]
      ,[Gender]
      ,[PlaceOfBirth]
      ,[FatherName]
      ,[MotherName]
      ,[Address]
      ,[RegistrationDate]
  FROM [BirthCertificateDB].[dbo].[BirthCertificatedb]
